###################################
#服务启动端口的配置
###################################
server:
  port: ${server-port}

###############################################################
# eureka 的相关配置
# 如果不需要 结合eureka 使用，可以不要这一段配置
###############################################################
eureka:
  client:
    fetch-registry: true
    register-with-eureka: ${register-with-eureka}     # 是否注册到eureka
    service-url:
      defaultZone: ${service-url-defaultZone}
  instance:
    prefer-ip-address: false
    hostname: ${instance-hostname}


spring:
  cloud:
#################################
#   gateway相关配置
#################################
    gateway:
#    路由定义
      routes:

      - id: baidu
        uri: https://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
        - StripPrefix=1

      - id: eureka-manage
        uri: lb://eureka-manage
        predicates:
        - Path=/eureka-manage/**
        filters:
        - StripPrefix=1

      - id: sina
        uri: https://www.sina.com.cn/
        predicates:
        - Path=/sina/**
        filters:
        - StripPrefix=1

org:
  my:
    jwt:
      #跳过认证的路由
      skip-auth-urls:
      - /baidu
      ############################################
      #   有效时长
      #     单位：d:天、h:小时、m:分钟、s:秒
      ###########################################
      effective-time: 1m